version: 2

builds:
  - ldflags: "-s -w"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

dockers:
  - build_flag_templates:
      - "--platform=linux/arm64,linux/amd64"
    image_templates:
      - ghcr.io/cedws/nyse-trade-halts:latest
      - ghcr.io/cedws/nyse-trade-halts:{{ .Tag }}

scoops:
  - name: nyse-trade-halts
    repository:
      name: scoop-bucket
      owner: cedws
      token: "{{ .Env.SCOOP_BUCKET_PUSH_TOKEN }}"

homebrew_casks:
  - name: nyse-trade-halts
    repository:
      name: homebrew-tap
      owner: cedws
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
    custom_block: |
      binary "nyse-trade-halts", target: "age-plugin-nyse-trade-halts"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nyse-trade-halts"]
          end

changelog:
  use: github-native
