version: 2

builds:
  - ldflags: "-s -w"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

dockers_v2:
  - images:
      - 'ghcr.io/{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}/{{ .ProjectName }}'
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    build_args:
      PROJECT_NAME: "{{ .ProjectName }}"
    flags:
      - "--pull"

scoops:
  - repository:
      name: scoop-bucket
      owner: '{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}'
      token: "{{ .Env.SCOOP_BUCKET_PUSH_TOKEN }}"

homebrew_casks:
  - repository:
      name: homebrew-tap
      owner: '{{ envOrDefault "GITHUB_REPOSITORY_OWNER" "cedws" }}'
      token: "{{ .Env.HOMEBREW_TAP_PUSH_TOKEN }}"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{ .ProjectName }}"]
          end

changelog:
  use: github
